/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenceRouteImport } from './routes/agence'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as EquipeIndexRouteImport } from './routes/equipe/index'
import { Route as EquipeSlugRouteImport } from './routes/equipe/$slug'
import { Route as ProprietesIndexRouteImport } from './routes/proprietes/index'
import { Route as ProprietesSlugRouteImport } from './routes/proprietes/$slug'
import { Route as QuartiersIndexRouteImport } from './routes/quartiers/index'
import { Route as QuartiersSlugRouteImport } from './routes/quartiers/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceRoute = AgenceRouteImport.update({
  id: '/agence',
  path: '/agence',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeSlugRoute = EquipeSlugRouteImport.update({
  id: '/equipe/$slug',
  path: '/equipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietesIndexRoute = ProprietesIndexRouteImport.update({
  id: '/proprietes/',
  path: '/proprietes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietesSlugRoute = ProprietesSlugRouteImport.update({
  id: '/proprietes/$slug',
  path: '/proprietes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartiersIndexRoute = QuartiersIndexRouteImport.update({
  id: '/quartiers/',
  path: '/quartiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartiersSlugRoute = QuartiersSlugRouteImport.update({
  id: '/quartiers/$slug',
  path: '/quartiers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/services': typeof ServicesRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/proprietes/$slug': typeof ProprietesSlugRoute
  '/quartiers/$slug': typeof QuartiersSlugRoute
  '/equipe/': typeof EquipeIndexRoute
  '/proprietes/': typeof ProprietesIndexRoute
  '/quartiers/': typeof QuartiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/services': typeof ServicesRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/proprietes/$slug': typeof ProprietesSlugRoute
  '/quartiers/$slug': typeof QuartiersSlugRoute
  '/equipe': typeof EquipeIndexRoute
  '/proprietes': typeof ProprietesIndexRoute
  '/quartiers': typeof QuartiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/services': typeof ServicesRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/proprietes/$slug': typeof ProprietesSlugRoute
  '/quartiers/$slug': typeof QuartiersSlugRoute
  '/equipe/': typeof EquipeIndexRoute
  '/proprietes/': typeof ProprietesIndexRoute
  '/quartiers/': typeof QuartiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agence'
    | '/services'
    | '/equipe/$slug'
    | '/proprietes/$slug'
    | '/quartiers/$slug'
    | '/equipe/'
    | '/proprietes/'
    | '/quartiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agence'
    | '/services'
    | '/equipe/$slug'
    | '/proprietes/$slug'
    | '/quartiers/$slug'
    | '/equipe'
    | '/proprietes'
    | '/quartiers'
  id:
    | '__root__'
    | '/'
    | '/agence'
    | '/services'
    | '/equipe/$slug'
    | '/proprietes/$slug'
    | '/quartiers/$slug'
    | '/equipe/'
    | '/proprietes/'
    | '/quartiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenceRoute: typeof AgenceRoute
  ServicesRoute: typeof ServicesRoute
  EquipeSlugRoute: typeof EquipeSlugRoute
  ProprietesSlugRoute: typeof ProprietesSlugRoute
  QuartiersSlugRoute: typeof QuartiersSlugRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
  ProprietesIndexRoute: typeof ProprietesIndexRoute
  QuartiersIndexRoute: typeof QuartiersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence': {
      id: '/agence'
      path: '/agence'
      fullPath: '/agence'
      preLoaderRoute: typeof AgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/equipe'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$slug': {
      id: '/equipe/$slug'
      path: '/equipe/$slug'
      fullPath: '/equipe/$slug'
      preLoaderRoute: typeof EquipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietes/': {
      id: '/proprietes/'
      path: '/proprietes'
      fullPath: '/proprietes/'
      preLoaderRoute: typeof ProprietesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietes/$slug': {
      id: '/proprietes/$slug'
      path: '/proprietes/$slug'
      fullPath: '/proprietes/$slug'
      preLoaderRoute: typeof ProprietesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quartiers/': {
      id: '/quartiers/'
      path: '/quartiers'
      fullPath: '/quartiers/'
      preLoaderRoute: typeof QuartiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quartiers/$slug': {
      id: '/quartiers/$slug'
      path: '/quartiers/$slug'
      fullPath: '/quartiers/$slug'
      preLoaderRoute: typeof QuartiersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenceRoute: AgenceRoute,
  ServicesRoute: ServicesRoute,
  EquipeSlugRoute: EquipeSlugRoute,
  ProprietesSlugRoute: ProprietesSlugRoute,
  QuartiersSlugRoute: QuartiersSlugRoute,
  EquipeIndexRoute: EquipeIndexRoute,
  ProprietesIndexRoute: ProprietesIndexRoute,
  QuartiersIndexRoute: QuartiersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
